services:
  - type: web
    name: gestao-alunos
    runtime: python
    plan: free
    branch: modulo-iii
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeployTrigger: commit

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gestao-alunos-db
          property: connectionString

      - key: JWT_SECRET
        generateValue: true

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"

      - key: ADMIN_USERNAME
        value: admin

      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: gestao-alunos-db
    plan: free
    databaseName: gestao_alunos
